services:
    # Helper services
    mu_news_module.archive_helper:
        class: MU\NewsModule\Helper\ArchiveHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@mu_news_module.entity_factory"
            - "@mu_news_module.workflow_helper"
            - "@mu_news_module.hook_helper"
    
    mu_news_module.category_helper:
        class: MU\NewsModule\Helper\CategoryHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_categories_module.category_registry_repository"
            - "@zikula_categories_module.api.category_permission"
    
    mu_news_module.collection_filter_helper:
        class: MU\NewsModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_users_module.current_user"
            - "@mu_news_module.category_helper"
            - "@=service('zikula_extensions_module.api.variable').get('MUNewsModule', 'showOnlyOwnEntries', false)"
            - "@=service('zikula_extensions_module.api.variable').get('MUNewsModule', 'filterDataByLocale', false)"
    
    mu_news_module.controller_helper:
        class: MU\NewsModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_news_module.archive_helper"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_news_module.entity_factory"
            - "@mu_news_module.collection_filter_helper"
            - "@mu_news_module.model_helper"
            - "@mu_news_module.image_helper"
            - "@mu_news_module.feature_activation_helper"
    
    mu_news_module.entity_display_helper:
        class: MU\NewsModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_news_module.listentries_helper"
    
    mu_news_module.feature_activation_helper:
        class: MU\NewsModule\Helper\FeatureActivationHelper
        arguments:
            - "@zikula_extensions_module.api.variable"
    
    mu_news_module.hook_helper:
        class: MU\NewsModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    mu_news_module.image_helper:
        class: MU\NewsModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    mu_news_module.listentries_helper:
        class: MU\NewsModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    mu_news_module.model_helper:
        class: MU\NewsModule\Helper\ModelHelper
        arguments:
            - "@mu_news_module.entity_factory"
    
    mu_news_module.notification_helper:
        class: MU\NewsModule\Helper\NotificationHelper
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@session"
            - "@router"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@twig"
            - "@zikula_mailer_module.api.mailer"
            - "@zikula_groups_module.group_repository"
            - "@mu_news_module.entity_display_helper"
            - "@mu_news_module.workflow_helper"
    
    mu_news_module.search_helper:
        class: MU\NewsModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@session"
            - "@request_stack"
            - "@mu_news_module.entity_factory"
            - "@mu_news_module.controller_helper"
            - "@mu_news_module.entity_display_helper"
            - "@mu_news_module.feature_activation_helper"
            - "@mu_news_module.category_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: MUNewsModule }
    
    mu_news_module.translatable_helper:
        class: MU\NewsModule\Helper\TranslatableHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_settings_module.locale_api"
            - "@mu_news_module.entity_factory"
    
    mu_news_module.upload_helper:
        class: MU\NewsModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@filesystem"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('MUNewsModule')"
            - "%datadir%"
    
    mu_news_module.view_helper:
        class: MU\NewsModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@mu_news_module.controller_helper"
    
    mu_news_module.workflow_helper:
        class: MU\NewsModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@mu_news_module.entity_factory"
            - "@mu_news_module.listentries_helper"
