services:
    # Twig extension
    mu_news_module.twig_extension:
        class: MU\NewsModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@mu_news_module.entity_display_helper"
            - "@mu_news_module.workflow_helper"
            - "@mu_news_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
